name: carloscazaresArt
favicon: null
layout_spectrum: 0
typography_spectrum: 0.54539
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dddbdc'
    - '#a4a8ab'
    - '#656a6f'
    - '#404040'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
